import { hasAny } from "./utils";

export function extractFlags(normalized) {
  return {
    severe: hasAny(normalized, [
      "severe",
      "very bad",
      "worst",
      "extreme",
      "cannot",
      "can't",
      "unbearable",
      "شديد",
      "قوي",
      "قاسي",
      "مرة",
      "جدا",
      "جداً",
      "مش قادر",
      "لا أستطيع",
      "ما بقدر",
    ]),
    child: hasAny(normalized, [
      "child",
      "kid",
      "baby",
      "infant",
      "newborn",
      "طفل",
      "رضيع",
      "بيبي",
      "مولود",
    ]),
    pregnant: hasAny(normalized, ["pregnant", "pregnancy", "حامل", "حمل"]),
    elderly: hasAny(normalized, [
      "old",
      "elderly",
      "senior",
      "كبير",
      "مسن",
      "عجوز",
    ]),
    duration: hasAny(normalized, [
      "day",
      "days",
      "week",
      "weeks",
      "month",
      "months",
      "today",
      "yesterday",
      "من امس",
      "من أمس",
      "يوم",
      "يومين",
      "ايام",
      "أيام",
      "اسبوع",
      "أسبوع",
      "شهر",
      "اليوم",
      "امبارح",
      "أمس",
    ]),
    breathing: hasAny(normalized, [
      "cant breathe",
      "can't breathe",
      "shortness of breath",
      "trouble breathing",
      "difficulty breathing",
      "ضيق تنفس",
      "صعوبة تنفس",
      "اختناق",
      "مش قادر اتنفس",
      "مش قادر أتنفس",
    ]),
    chest: hasAny(normalized, ["chest pain", "chest", "ألم صدر", "صدر"]),
    bleeding: hasAny(normalized, ["bleeding", "blood loss", "نزيف", "دم كثير"]),
    unconscious: hasAny(normalized, [
      "fainted",
      "unconscious",
      "passed out",
      "loss of consciousness",
      "فقدان وعي",
      "اغمي",
      "أغمي",
      "مغمى",
    ]),
  };
}

export function isEmergencyCase(normalized, flags) {
  if (flags.breathing || flags.chest || flags.bleeding || flags.unconscious) {
    return true;
  }

  return hasAny(normalized, [
    "stroke",
    "seizure",
    "choking",
    "severe bleeding",
    "heart attack",
    "suicidal",
    "جلطة",
    "تشنج",
    "اختناق",
    "نزيف شديد",
    "ذبحة",
    "انتحار",
    "حرق شديد",
    "حادث",
    "accident",
  ]);
}
